### ISSUE TITLE
Grunddaten zur Inventur im Aufnahmeformular

### ISSUE THREAD

**Issue by twiebke** [b-lack/lfb-regeneration_wildlife_impact_monitoring#16]
Jeder Unternehmer bekommt einen Datensatz indem im wesentlichen die 
- Daten zur Punktgeometrie mit dem Schlüssel (h3index), 
- die Losnummer und das Aufnahmejahr und für Folgeinventuren: 
- die Daten der Baumplots, Landmarken, permanenten Markierungen  sowie Datenfelder für die Aufnahmen enthalten sind. 
- Ein Datenfeld ist die "unterlosnr"

- [x]   Die Punkte müssen in QGIS sichtbar und entsprechend ihres über den Workflow abgebildeten Zustandes Symbolisiert werden
- [x] Die Unterlosnummer muss von den Unternehmern in QGIS verändert werden können
- [x] Bei Wiederholungsinventuren müssen die Daten der Baum- und Landmarkenplots in qgis kartographisch und im Aufnahmeformular dargestellt und verändert werden können
- [ ] #21
- [x] #20

**Comment by b-lack** [comment]
Wurde in #21 verschoben.
