### ISSUE TITLE
Python fehler beim Start

### ISSUE THREAD

**Issue by twiebke** [b-lack/lfb-regeneration_wildlife_impact_monitoring#17]
Ich konnte das Plugin regulär starten, öffnete dann ein leeres Projekt, lud ein geopackage layer und erhalte nach Start des Plugins:
`2023-06-26T18:34:17     WARNING    Traceback (most recent call last):
              File "/home/torsten/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lfb_regeneration_wildlife_impact/lfb_regeneration_wildlife_impact.py", line 235, in run
              self.dlg.update()
             AttributeError: 'LfbRegenerationWildlifeImpact' object has no attribute 'dlg'`

**Comment by b-lack** [comment]
Generell gilt, dass die Versionen nicht kompatibel sein müssen. D.h. alte Layer, welche vom Plugin generiert werden, müssen gelöscht werden, bevor du das Plugin öffnest.

**Comment by b-lack** [comment]
Sollte der Fehler in einer neuen Version erneut auftauchen bitte issue erneut öffnen.
