### ISSUE TITLE
Linus: Heterogenitätsgrad 

### ISSUE THREAD

**Issue by b-lack** [b-lack/lfb-regeneration_wildlife_impact_monitoring#48]
der Heterogenitätsgrad fängt soweit ich weiß erst bei 1 an, der Wert 0 sollte nicht möglich sein, sprich da aber besser nochmal mit @twiebke , da gab's widersprüchliche Aussagen in der Vergangenheit

**Comment by twiebke** [comment]
0 = homogen bis 10 = heterorgen -> es sind alle Werte von 0 - 10 möglich

Ist ein gutachtlicher Wert. In der Auswertung werde ich das irgendwie zusammenfassen müssen und Klassen bilden.
